name: Package for all platforms

on:
  push:
    tags: '*'

jobs:
  build:
    permissions: write-all
    name: Package for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install dependancies
        run: python3 -m pip install pyinstaller
      
      - name: Build package
        run: |
          python3 -m PyInstaller app.py --add-data "commands.py:noml" --add-data "editor.py:noml" --add-data "sysimps.py:noml" --hidden-import termios --hidden-import tty --onefile --name noml-${{ matrix.os }}

      - name: Upload files to a GitHub release (windows)
        if: matrix.os == 'windows-latest'
        uses: svenstaro/upload-release-action@2.7.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/noml-${{ matrix.os }}.exe
          asset_name: noml-${{ matrix.os }}.exe
          tag: ${{ github.ref }}
          overwrite: true
          body: ${{ github.event.release.body }}
          
      - name: Upload files to a GitHub release
        if: ${{ matrix.os != 'windows-latest' }}
        uses: svenstaro/upload-release-action@2.7.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/noml-${{ matrix.os }}
          asset_name: noml-${{ matrix.os }}
          tag: ${{ github.ref }}
          overwrite: true
          body: ${{ github.event.release.body }}
